from __future__ import annotations

from typing import Protocol


class BrokerAdapter(Protocol):
    def place_order(self, order: dict) -> dict: ...

    def cancel_order(self, broker_order_id: str) -> dict: ...

    def get_order_status(self, broker_order_id: str) -> dict: ...

    def get_fills(self, since: str | None = None) -> list[dict]: ...

    def get_balances(self) -> dict: ...

    def get_positions(self) -> list[dict]: ...
